name: Community Radar

on:
  schedule:
    - cron: '0 12 * * *'  # Täglich um 14:00 Uhr UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Community Radar Script
        run: python community_radar.py
